name: Main

on:
  push:
    branches:
      - canary
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.17, 20, 21]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check Types
        run: npm run type-check

      - name: Build
        run: npm run build
  test:
    name: Test with Node.js ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.17, 20, 21]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test

      - name: Upload code coverage
        uses: actions/upload-artifact@v4
        if: matrix.node == '21'
        with:
          name: coverage
          path: ./coverage
